sqroot: sqroot.cpp 
	g++ sqroot.cpp -o sqroot_n



# 
# Yes that is it.
# but this is also a very simple project
#
# The basic premise is that make works with targets
# the syntax above define a target called sqroot (left side of ':')
# that will be triggered when make notices that sqroot.cpp has changed
# (right side of ':')
#
